# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c6e54fb8003dd765696f61c667ee88e66dc7790f8ea80e25fe32b827102c4eeabb955497a99456e8895078b037d8b30c9441aa0591577905e9374a6b30e7cf2

test:
  secret_key_base: a2bfdd48e7c99021e50ea878beae51ac8c035395497b8a553fed5950d7a943194dc49c732e6730688aaade2090dbbd76e6c049dbca9274374b1475a6d462b510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
